// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKfYYgNx9OFLATNYgcF0b_UwUMynIu3LI',
    appId: '1:1067136083727:web:e7aabcd13403b91979007a',
    messagingSenderId: '1067136083727',
    projectId: 'note-app-943e2',
    authDomain: 'note-app-943e2.firebaseapp.com',
    storageBucket: 'note-app-943e2.appspot.com',
    measurementId: 'G-WQZDP2EF2B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1DsRt7rXMDbIPVfI9Cx0WdsbDI6o0wQU',
    appId: '1:1067136083727:android:8f5882047da0a80579007a',
    messagingSenderId: '1067136083727',
    projectId: 'note-app-943e2',
    storageBucket: 'note-app-943e2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyByfrRVnizM29XOAkjySgOqTRydvfEKoPM',
    appId: '1:1067136083727:ios:8bb7579d1609f5e679007a',
    messagingSenderId: '1067136083727',
    projectId: 'note-app-943e2',
    storageBucket: 'note-app-943e2.appspot.com',
    iosClientId: '1067136083727-n699qo834uvtomg9pfo80ns4kdu9m3n6.apps.googleusercontent.com',
    iosBundleId: 'com.example.toDo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyByfrRVnizM29XOAkjySgOqTRydvfEKoPM',
    appId: '1:1067136083727:ios:e8fb398d255a569479007a',
    messagingSenderId: '1067136083727',
    projectId: 'note-app-943e2',
    storageBucket: 'note-app-943e2.appspot.com',
    iosClientId: '1067136083727-juj2396namn4v46qrl8rjv1jf9htl5fe.apps.googleusercontent.com',
    iosBundleId: 'com.example.toDo.RunnerTests',
  );
}
